#!/bin/bash
source ~/.bashrc


project="$1"
type="$2"


git --work-tree="/home/yooneskh/$project/" --git-dir="/home/yooneskh/$project/.git" checkout -f

cd /home/yooneskh/$project


if [ "$type" == "ts-server" ]; then
  yarn && yarn build && pm2 restart --update-env $project
fi

if [ "$type" == "js-server" ]; then
  yarn && pm2 restart --update-env $project
fi

if [ "$type" == "js-server-npm" ]; then
  npm install && pm2 restart --update-env $project
fi

if [ "$type" == "deno-server" ]; then
  deno cache bootstrap.ts && deno check bootstrap.ts && pm2 restart --update-env $project
fi

if [ "$type" == "deno-js-server" ]; then
  deno cache bootstrap.js && deno check bootstrap.js && pm2 restart --update-env $project
fi

if [ "$type" == "nuxt-server" ]; then
  yarn && yarn build && pm2 restart --update-env $project
fi
